{% set name = "geoarrow-c" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a488794aab6631f5c54c3f77fcff734b2dda162e2ef74cd22fff6989d7aed89d

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3.1.0                         # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools >=61.0.0
    - setuptools-scm
    - cython <3.1.0
    - pip
    - libcxx
  run:
    - python
    - libcxx

test:
  imports:
    - geoarrow.c
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/geoarrow/geoarrow-c
  summary: Low-level Python bindings to the GeoArrow C implementation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - paleolimbot
